import "./globals.css";
import "../style/index.scss";
import AppProvider from "@/contextApi/AppProvider";
import { ToastContainer } from "react-toastify";
// Importamos tu nuevo AuthProvider
import { AuthProvider } from "@/utils/AuthContext";
import QueryProvider from "@/utils/QueryProvider";
import 'react-toastify/dist/ReactToastify.css';

export const metadata = {
  title: "E-Shop Marketplace", // Cambiamos el título por defecto
  description: "Marketplace moderno generado con Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <meta httpEquiv="x-ua-compatible" content="ie=edge" />
        <meta name="description" content="Generated by create next app" />
        {/* Cambiamos noindex por index para que Google sí te encuentre */}
        <meta name="robots" content="index, follow" /> 
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1, shrink-to-fit=no"
        />
        <link rel="icon" href="/favicon.png" />
        <link rel="stylesheet" href="/assets/css/fontAwesome5Pro.css" />
        <link
          href="https://fonts.googleapis.com/css2?family=Urbanist:wght@300;400;500;600;700;800;900&display=swap"
          rel="stylesheet"
        />
      </head>

      <body className="body-bg" suppressHydrationWarning={true}>
        <AppProvider>
          {/* QueryProvider envuelve a AuthProvider para que los hooks de React Query
              (incluido el futuro useCurrentUser de Fase 1) tengan QueryClient disponible. */}
          <QueryProvider>
            <AuthProvider>
              {children}
            </AuthProvider>
          </QueryProvider>
        </AppProvider>
        <ToastContainer 
          position="bottom-right" 
          autoClose={3000} 
          theme="dark" 
        />
      </body>
    </html>
  );
}