import React from "react";
import Link from "next/link";
import ThemeChanger from "../home/ThemeChanger";
import Breadcrumbs from "@/utils/Breadcrumbs";
import Image from "next/image";
import wallet1 from "../../../public/assets/img/wallet/wallet1.png";
import wallet2 from "../../../public/assets/img/wallet/wallet2.png";
import wallet3 from "../../../public/assets/img/wallet/wallet3.png";
import wallet4 from "../../../public/assets/img/wallet/wallet4.png";
import wallet5 from "../../../public/assets/img/wallet/wallet5.png";
import wallet6 from "../../../public/assets/img/wallet/wallet6.png";
const WalletConnectMain = () => {
  const walletConnect = [
    {
      walletTitle: "Wallet Connect",
      walletImage: wallet1,
      walletDesc:
        "Sale your single item to increase your currencies that generated by crypto currency.",
      walletBtn: "Connect",
    },
    {
      walletTitle: "Metamask",
      walletImage: wallet2,
      walletDesc:
        "Sale your single item to increase your currencies that generated by crypto currency.",
      walletBtn: "Connect",
    },
    {
      walletTitle: "Fortmatic",
      walletImage: wallet3,
      walletDesc:
        "Sale your single item to increase your currencies that generated by crypto currency.",
      walletBtn: "Connect",
    },
    {
      walletTitle: "Torus",
      walletImage: wallet4,
      walletDesc:
        "Sale your single item to increase your currencies that generated by crypto currency.",
      walletBtn: "Connect",
    },
    {
      walletTitle: "Bitski",
      walletImage: wallet5,
      walletDesc:
        "Sale your single item to increase your currencies that generated by crypto currency.",
      walletBtn: "Connect",
    },
    {
      walletTitle: "Coinbase",
      walletImage: wallet6,
      walletDesc:
        "Sale your single item to increase your currencies that generated by crypto currency.",
      walletBtn: "Connect",
    },
  ];
  return (
    <main>
      <ThemeChanger />
      <Breadcrumbs
        breadcrumbTitle="Connect Wallet"
        breadcrumbSubTitle="Connect Wallet"
      />

      <section className="connect-wallet-area pt-130 pb-120">
        <div className="container">
          <div className="connect-wallet-wrapper">
            {walletConnect && (
              <div className="row">
                {walletConnect.map((WalletConnectMain, num) => (
                  <div key={num} className="col-xl-4 col-lg-4 col-md-6">
                    <div className="box-card-single box-card-wallet mb-40 wow fadeInUp">
                      <div className="box-card-inner text-center">
                        <div className="box-card-icon">
                          <Image
                            width={50}
                            height={50}
                            style={{ width: "auto", height: "auto" }}
                            src={WalletConnectMain?.walletImage}
                            alt="Img Not Found"
                          />
                        </div>
                        <h4 className="box-card-title">
                          {WalletConnectMain.walletTitle}
                        </h4>
                        <p>{WalletConnectMain.walletDesc}</p>
                        <div className="box-card-btn">
                          <a href="#" className="fill-btn-lightblue">
                            {WalletConnectMain.walletBtn}
                          </a>
                        </div>
                      </div>
                    </div>
                  </div>
                ))}
              </div>
            )}
            <div className="wallet-wrapper-note text-center wow fadeInUp">
              <div className="note">
                Need help to collect wallet?{" "}
                <Link className="text-btn" href="/contact">
                  Contact Support
                </Link>{" "}
                or Lean how to collect wallet visiting to our{" "}
                <Link className="text-btn" href="/faq">
                  FAQ page
                </Link>
              </div>
            </div>
          </div>
        </div>
      </section>
    </main>
  );
};

export default WalletConnectMain;
